CREATE SEQUENCE produtos_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE produtos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    preco DOUBLE NOT NULL,
    quantidade INT NOT NULL
);

